### ISSUE TITLE
snapper threading does not always work

### ISSUE THREAD

**Issue by rbouckaert** [rbouckaert/snapper#3]
When a nucleotide alignment is imported in BEAUti, it runs with a single thread, but fails when running with multiple threads with a NullPointerException. This should be fixed.

**Comment by CMWbio** [comment]
Dear Remco,

Any estimation on your timeline for this fix?


Cheers,

Chris

**Comment by rbouckaert** [comment]
c1035ff7e9139039509e6f5225a57421807d276b may have done this.

**Comment by MarnusStoltz** [comment]
Yes, the latest SNAPPER can now handle missing data and multithreading is
also working.

Please let us know if any bugs pop-up.

**Comment by davidjamesbryant** [comment]
BIFFF!!!!!

=======================
Prof David Bryant
Dept Mathematics and Statistics
University of Otago
Aotearoa New Zealand

On 28/06/2021, at 8:40 PM, Marnus_Stoltz ***@***.***> wrote:

﻿

Yes, the latest SNAPPER can now handle missing data and multithreading is
also working.

Please let us know if any bugs pop-up.

**Comment by CMWbio** [comment]
Thanks very much!

**Comment by bmichanderson** [comment]
Multithreading is not working for me with BEAST 2.6.6 and SNAPPER 1.0.2 on Linux (Ubuntu 20.04) and Windows 10 using the tutorial example files (https://github.com/BEAST2-Dev/beast-docs/releases/download/v1.0/snapper-delimitation-tutorial-2021.zip). 
The command:
`path/to/beast -threads 6 RunA.xml`
The error produced:
```s
Error 110 parsing the xml input file

validate and intialize error: initAndValidate() failed! Index 0 out of bounds for length 0

Error detected about here:
  <beast>
      <run spec='beast.inference.PathSampler'>
          <mcmc id='mcmc' spec='MCMC'>
              <distribution id='posterior' spec='util.CompoundDistribution'>
                  <distribution id='likelihood' spec='util.CompoundDistribution'>
                      <distribution id='snapperTreeLikelihood.hemi129' spec='snapper.SnapperTreeLikelihood'>
```

**Comment by MarnusStoltz** [comment]
Hi Ben,

Please try SNAPPER 1.0.1 - there might be an update that broke it again.

Thanks
Marnus

**Comment by bmichanderson** [comment]
Hi Marnus,

Using SNAPPER 1.0.1 now gives the following error:

```s
java.lang.ClassCastException: snap.Data cannot be cast to snapper.Data
        at snapper.SnapperTreeLikelihood.initAndValidate(Unknown Source)
        at beast.util.XMLParser.initBEASTObjects(Unknown Source)
        at beast.util.XMLParser.parse(Unknown Source)
        at beast.util.XMLParser.parseFile(Unknown Source)
        at beast.app.BeastMCMC.parseArgs(Unknown Source)
        at beast.app.beastapp.BeastMain.main(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at beast.app.beastapp.BeastLauncher.run(Unknown Source)
        at beast.app.beastapp.BeastLauncher.main(Unknown Source)

Error 110 parsing the xml input file

validate and intialize error: snap.Data cannot be cast to snapper.Data

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='likelihood' spec='util.CompoundDistribution'>
                  <distribution id='snapperTreeLikelihood.hemi129' spec='snapper.SnapperTreeLikelihood'>
```

**Comment by MarnusStoltz** [comment]
Hi Ben,

Apologies for the late response, but if you use snapper 1.0.1 then you
should change all class references from snap.data class to snapper.data
in your xml.

Happy to help you get it up and running if it doesn't work.

Cheers
Marnus

**Comment by bmichanderson** [comment]
Hi Marnus,

I changed the `RunA.xml` file from the tutorial at line 71 to `spec="snapper.Data"` and it no longer has the error for being unable to cast the data. It gives a new error instead (no threads):

```s
java.lang.ArrayIndexOutOfBoundsException: 30
        at snapper.SnapperLikelihoodCore.setLeafPolyFactors(Unknown Source)
        at snapper.SnapperTreeLikelihood.initAndValidate(Unknown Source)
        at beast.util.XMLParser.initBEASTObjects(Unknown Source)
        at beast.util.XMLParser.parse(Unknown Source)
        at beast.util.XMLParser.parseFile(Unknown Source)
        at beast.app.BeastMCMC.parseArgs(Unknown Source)
        at beast.app.beastapp.BeastMain.main(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at beast.app.beastapp.BeastLauncher.run(Unknown Source)
        at beast.app.beastapp.BeastLauncher.main(Unknown Source)

Error 110 parsing the xml input file

validate and intialize error: 30

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='likelihood' spec='util.CompoundDistribution'>
                  <distribution id='snapperTreeLikelihood.hemi129' spec='snapper.SnapperTreeLikelihood'>
```

When trying with `-threads 8` I get a similar error:

```s
java.lang.ArrayIndexOutOfBoundsException: 30
        at snapper.SnapperLikelihoodCore.setLeafPolyFactors(Unknown Source)
        at snapper.SnapperTreeLikelihood.initAndValidate(Unknown Source)
        at beast.core.BEASTInterface.initByName(Unknown Source)
        at snapper.SnapperTreeLikelihood.initAndValidate(Unknown Source)
        at beast.util.XMLParser.initBEASTObjects(Unknown Source)
        at beast.util.XMLParser.parse(Unknown Source)
        at beast.util.XMLParser.parseFile(Unknown Source)
        at beast.app.BeastMCMC.parseArgs(Unknown Source)
        at beast.app.beastapp.BeastMain.main(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at beast.app.beastapp.BeastLauncher.run(Unknown Source)
        at beast.app.beastapp.BeastLauncher.main(Unknown Source)
java.lang.RuntimeException: initAndValidate() failed! 30
        at beast.core.BEASTInterface.initByName(Unknown Source)
        at snapper.SnapperTreeLikelihood.initAndValidate(Unknown Source)
        at beast.util.XMLParser.initBEASTObjects(Unknown Source)
        at beast.util.XMLParser.parse(Unknown Source)
        at beast.util.XMLParser.parseFile(Unknown Source)
        at beast.app.BeastMCMC.parseArgs(Unknown Source)
        at beast.app.beastapp.BeastMain.main(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at beast.app.beastapp.BeastLauncher.run(Unknown Source)
        at beast.app.beastapp.BeastLauncher.main(Unknown Source)

Error 110 parsing the xml input file

validate and intialize error: initAndValidate() failed! 30

Error detected about here:
  <beast>
      <run id='mcmc' spec='MCMC'>
          <distribution id='posterior' spec='util.CompoundDistribution'>
              <distribution id='likelihood' spec='util.CompoundDistribution'>
                  <distribution id='snapperTreeLikelihood.hemi129' spec='snapper.SnapperTreeLikelihood'>
```

**Comment by bmichanderson** [comment]
Hi,
Any progress on this bug? Any suggested alternatives?
Cheers,
Ben

**Comment by felixgrewe** [comment]
Hi,

I tried snapper 1.0.0 and 1.0.2 on Ubuntu Linux and multithreading did not work for me. A single thread (without the -threads option) worked. I would also like to know if you plan on fixing this or if there is any alternative.

Thanks,
Felix

**Comment by hwherrmann** [comment]
Hello,
I have the same issue with multi-threading SNAPPER. However, when I run it on my Mac the activity monitor shows that Beast is using 25 threads?
With -threads I get the same error messages as above. Is there a fix in sight?

**Comment by davidjamesbryant** [comment]
HI there,
I was involved in the multi-threading coding, but I'll try and have a look and see what is happening. No promises though...

The multithreading is only a linear-in-number-of-threads speedup (it evaluates different site patterns on different threads), so you can get a comparable speedup by running multiple chains in parallel.

cheers,

David.

**Comment by fcsalgado** [comment]
Hi David, 

If I run multiple chains in parallel as you suggested, how can I calculate the marginal likelihood estimate to compare between models?

Thanks for your help, 

Best, 

Fabian

**Comment by davidjamesbryant** [comment]
Hi Fabian,

In principle, you should be able to remove burnin from each of the chains individually and then concatenate them to compute the marginal likelihood. Remco – is that going to be plausible software wise?

-David.


From: Fabian_Salgado_Roa ***@***.***>
Date: Monday, 4 April 2022 at 7:20 PM
To: rbouckaert/snapper ***@***.***>
Cc: David Bryant ***@***.***>, Comment ***@***.***>
Subject: Re: [rbouckaert/snapper] snapper threading does not always work (#3)

Hi David,

If I run multiple chains in parallel as you suggested, how can I calculate the marginal likelihood estimate to compare between models?

Thanks for your help,

Best,

Fabian

**Comment by rbouckaert** [comment]
Marginal likelihoods can be calculated using the [model selection](https://github.com/BEAST2-Dev/model-selection) or [nested sampling](https://github.com/BEAST2-Dev/nested-sampling) package, but cannot be estimated directly from an MCMC run. If you are interested in species delimitation, you might want to have a look at [SPEEDEMON](https://github.com/rbouckaert/speedemon) -- the paper is under review, but a [preprint](https://www.biorxiv.org/content/10.1101/2022.02.14.480439v1.abstract) is available.

**Comment by bmichanderson** [comment]
Thanks Remco and David. 

SPEEDEMON looks promising. So, if I run multiple chains in parallel, how do I use the output with SPEEDEMON? Do I simply cut a burn-in out of each of the *.trees files and then concatenate them together?

Based on my data (150 individuals / 33 "species" and ~4k SNPs), 1 million samples will take about 1500 h (~60 days). This drops to about 400 h (~16 days) if I randomly down sample my SNPs to 1k. To speed this up, does it make sense to run a bunch of chains of ~200k and then concatenate the results? I guess that might depend on convergence?

Cheers,

Ben

**Comment by rbouckaert** [comment]
Hi Ben,

Regardless of the MCMC analysis, it is good practice to run multiple chains to make sure that each of them converge to the same distribution. You can simply check this in Tracer and look at the distributions of each of the parameters that are logged -- if they look mostly the same that gives some confidence of convergence, but even then it cannot be guaranteed.

So, you want to run multiple chains anyway, and can concatenate them with the `LogCombiner` tool that comes with BEAST. Your approach makes sense, but relies on each the chains to have burn-in removed. You can use Tracer to see how much burn-in needs to be removed from each of the chains.

Cheers,

Remco

**Comment by k-sanchez** [comment]
Hi there,
I'm having the same problem running speedemon with SNP data and the `-threads` option activated in a cluster (BEAST v2.7.3, snapper v1.1.0, speedemon v1.1.0)
When I perform a multithreaded analysis on my laptop, the problem disappears (the same package versions are installed on both devices)
What could be the reason?
thanks,

**Comment by rbouckaert** [comment]
@k-sanchez It would be useful to know the type of exception that is thrown to diagnose the problem. 

BEAST should behave the same on any computer, and there is nothing that comes to mind immediately that could explain the differences in behaviour. 

Do you have any detail about the error message that you get on the cluster? 

Cheers, Remco

**Comment by k-sanchez** [comment]
Dear Remco and others, this problem has been solved with the recent release of Snapper that you mentioned [here](https://groups.google.com/g/beast-users/c/_4-Jcg-uICo/m/SgtFvQVnAQAJ). (I put the link here in case someone else has the same problem)

**Comment by rbouckaert** [comment]
Thanks for letting us know, Kevin!

I'll leave the issue open in case others run into similar problems, so they can report it here.

**Comment by RichPB** [comment]
I am using the latest snapper 1.1.2 under BEAST 2.7.4 to estimate a species tree and divergence times from SNP data and get a validate and intialize error ("Cannot load from object array because "this.m_nPatternLineageCounts" is null") when I use more than one thread. It works fine with just one thread.

Alignment(51885snp)
  47 taxa
  51885 sites
  41014 patterns

C3: 51885 13
C4: 51885 13
C5: 51885 15
C6: 51885 13
C7: 51885 11
C1: 51885 15
C2: 51885 21
Data(snapper.51885snp)
  7 taxa
  51885 sites
  8626 patterns

**java.lang.NullPointerException: Cannot load from object array because "this.m_nPatternLineageCounts" is null**
	at snapper.Data.getPatternLineagCounts(Unknown Source)
	at snapper.SnapperTreeLikelihood.getPatternLineagCounts(Unknown Source)
	at snapper.SnapperTreeLikelihood.initAndValidate(Unknown Source)
	at beast.base.parser.XMLParser.initBEASTObjects(Unknown Source)
	at beast.base.parser.XMLParser.parse(Unknown Source)
	at beast.base.parser.XMLParser.parseFile(Unknown Source)
	at beastfx.app.beast.BeastMCMC.parseArgs(Unknown Source)
	at beastfx.app.beast.Controller$2.run(Unknown Source)
beast.base.parser.XMLParserException: 
Error 110 parsing the xml input file

validate and intialize error: Cannot load from object array because "this.m_nPatternLineageCounts" is null

**Comment by rbouckaert** [comment]
@RichPB There is nothing immediately obvious to me from the code that could cause this.

Would you be able to make the XML available (or send to higgs.ml@gmail.com) so I can have a look at what is going on?

**Comment by rbouckaert** [comment]
The issue can be replicated by running an analysis from the BEAST GUI and setting `threads` to > 1 but leave `instances` at 1. Setting `instances` and `threads` to the same  value fixes this.
49da0ba78cfdb98a3748d7a02d8beab3484222db should have fixed the problem, but still requires users to specify both `threads` and `instances` in the GUI (from CLI instances is not set).
